CREATE TABLE applications (
    application_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id               BIGINT REFERENCES workers (worker_id),
    application_date        DATE,
    reason_for_unemployment VARCHAR(255),
    status                  VARCHAR(255)
);
