CREATE TABLE books (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255),
    author      VARCHAR(255),
    isbn        VARCHAR(255),
    price       DOUBLE PRECISION,
    description VARCHAR(255)
);
